FROM anibali/pytorch:cuda-9.0
RUN conda install jupyter
RUN conda install -c conda-forge matplotlib pandas scikit-learn
RUN conda install -c conda-forge ffmpeg ipywidgets
RUN conda remove --force numpy
RUN conda install -c conda-forge numpy=1.14.3

WORKDIR /home/nina/
USER root
CMD ["/home/user/miniconda/envs/py36/bin/jupyter", "notebook", "--allow-root", "--ip=0.0.0.0", "--NotebookApp.iopub_data_rate_limit=1.0e10"]
